// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7jgw7ehSiyP3t5HAwGWAu0rdIT6-t8f8',
    appId: '1:50536784750:web:80eb05edb181261a69d77f',
    messagingSenderId: '50536784750',
    projectId: 'magnum-bank',
    authDomain: 'magnum-bank.firebaseapp.com',
    storageBucket: 'magnum-bank.firebasestorage.app',
    measurementId: 'G-4VRY47E448',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkIVR1bnJTv1SA5yzjwUY1Nl8NQ8VuFko',
    appId: '1:50536784750:android:41b931fd1d22c59369d77f',
    messagingSenderId: '50536784750',
    projectId: 'magnum-bank',
    storageBucket: 'magnum-bank.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADGIMJ4kPR03Sq8eK8gByHhOmlBnt0cm8',
    appId: '1:50536784750:ios:5ea958e21052e56769d77f',
    messagingSenderId: '50536784750',
    projectId: 'magnum-bank',
    storageBucket: 'magnum-bank.firebasestorage.app',
    iosBundleId: 'com.example.magnumBank',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADGIMJ4kPR03Sq8eK8gByHhOmlBnt0cm8',
    appId: '1:50536784750:ios:5ea958e21052e56769d77f',
    messagingSenderId: '50536784750',
    projectId: 'magnum-bank',
    storageBucket: 'magnum-bank.firebasestorage.app',
    iosBundleId: 'com.example.magnumBank',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7jgw7ehSiyP3t5HAwGWAu0rdIT6-t8f8',
    appId: '1:50536784750:web:0cd555b5ef8bcdbe69d77f',
    messagingSenderId: '50536784750',
    projectId: 'magnum-bank',
    authDomain: 'magnum-bank.firebaseapp.com',
    storageBucket: 'magnum-bank.firebasestorage.app',
    measurementId: 'G-K7H4T0040R',
  );
}
